name: Wiki Import Automation
run-name: Uploading game info to wiki
on:
    push:
      branches:
        - wiki
jobs:
    import-game-info-to-wiki:
        name: Uploading game info to wiki
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
              with:
                repository: ${{ github.repository }}
                path: bta
            - name: Export info
              env:
                WIKI_PASS: ${{ secrets.WIKI_PASS }}
                WIKI_USER: ${{ secrets.WIKI_USER}}
              run: |
                echo "Downloading importer"
                TAG=$(curl -s https://api.github.com/repos/BattleTech-Advanced-3062/bta-wiki-import/releases/latest | jq -r '.tag_name')
                wget https://github.com/BattleTech-Advanced-3062/bta-wiki-import/releases/download/${TAG}/bta-wiki-import_linux_amd64.tar.gz
                tar xvf bta-wiki-import_linux_amd64.tar.gz
                mkdir path-to-wikitext
                ./bta-wiki-import export ./bta/ ./path-to-wikitext/
                ./bta-wiki-import import  -l https://www.bta3062.com/api.php  ./path-to-wikitext/